### ISSUE TITLE
CMake build does not test for PugiXml

### ISSUE THREAD

**Issue by bvanevery** [gawag/Urho-Sample-Platformer#10]
In Visual Studio I get the following error:

```
1>C:\Users\BVANEVRY\devel\Urho-Sample-Platformer\gs_playing.cpp(4): fatal error C1083: Cannot open include file: 'Urho3D/ThirdParty/PugiXml/pugixml.hpp': No such file or directory
```

Although Urho3D uses pugixml.hpp in its build, by design it does not install pugixml.hpp for the benefit of consumers of Urho3D.  In Urho3D-1.4\Source\ThirdParty\PugiXml\CMakeLists.txt its installation is explicitly marked BUILD_TREE_ONLY.  You should either detect it yourself, provide it yourself, or file an upstream feature request that it always be installed with Urho3D.  I can think of some reasons why they may not wish to do that though, such as people having their own PugiXml libs on their system.  On Windows there is no pile of open source libs and include files generally available, which is why I'd be seeing this bug.

**Comment by damu** [comment]
Oh PugiXML is optional for Urho. I don't remember activating that specifically though... Is it sometimes included per default and sometimes not? I'm also using Windows.
I'll also include it in USP to be independent from that.

PugiXML 1.5 is now inside an include folder in USP. Oh I'm not sure if CMake is finding and using that .cpp file though.

**Comment by bvanevery** [comment]
AFAICT PugiXml is compiled unconditionally within Urho3D 1.4.  However it is not exported, it seems to be for Urho3D's internal consumption.  You've crushed the bug now though.

**Comment by damu** [comment]
Ah, ok.
Though the three files are not recognized by CMake and therefore not added to the project and build. I tried fixing that via CMake scripting but no success.
This should lead to linker errors if Urho would not be compiled with PugiXml. Although properly including and compiling these files could also lead to linker errors regarding double definitions as Urho and USP would have defined the PugiXml functions by compiling the .cpp.

But it works now which is fine. The proper solution would be the previous: using the files inside Urho and Urho properly providing the header files.

**Comment by bvanevery** [comment]
I haven't looked at whether there's some reason Urho3D _should_ expose PugiXml .h files?  Just because they use it internally, and you want to use it, doesn't mean they should be offering it up.  It would be a design issue; you could take it up with them.  I just wanted to get the build actually working.
