### ISSUE TITLE
Play button does not work

### ISSUE THREAD

**Issue by bvanevery** [gawag/Urho-Sample-Platformer#14]
When I build against Urho3D 1.5+ development version on Windows 7 with VS2015, the resulting program runs.  A sound is heard in the background that might be wood burning in a fire.  I get a menu screen with a black background, a large grey rectangle with a blue border that is blank, and 2 grey blue bordered rectangle buttons underneath it.  The left button says Play and the right says Quit.  Quit works fine.  Play does nothing at all.

I tried running the Debug version in Visual Studio 2015.  Clicking on Play doesn't generate any output messages in the debugger.  Not that it was supposed to, I was just hoping that perhaps it did.

**Comment by damu** [comment]
That's odd. Does the right button quit? You also don't see the list? Are there three text files in "Build\bin\Data\maps"? Is something different when you start the program directly from "Build/bin/Urho-Sample-Platformer.exe"?
It should look like: http://i.imgur.com/A5O1tzf.jpg
There is a rotating flag in the middle. The scene is brighter at the start, the "HDR" effects takes like 2 seconds to adapt.

**Comment by bvanevery** [comment]
As I said, Quit works fine, it quits.  There is no list.  There is no background scene either, it's black.

There is no such directory as Build\bin in my build directory.  I think this must be the problem.  You have assumed an "in-source" build, that people will be building in the \Urho-Sample-Platformer directory.  I'm not; I'm doing a so-called "out-of-source build" which is typical of idiomatic CMake usage.  The purpose of an out-of-source build is to avoid polluting the source tree.  

There are, however, 3 .xml files in my \build\Urho-Sample-Platformer\bin\Data\maps directory.  level_1.xml level_2.xml level_3.xml.  It's interesting that those \bin\Data and \bin\CoreData subdirectories exist and are populated.  If you didn't do that, then I think those Urho3D .cmake commands are automagically moving stuff around.

Suggest changing your stuff so that it works with only a \bin directory, no \Build\bin.

**Comment by damu** [comment]
I just did a test again by running cmake again after clearing my Build directory. The three map files are automatically copied from bin/Data/maps to my build directory's bin/Data/maps. Is the rest copied from bin/Data? Could be a reason why you also have no background scene.

**Comment by bvanevery** [comment]
\bin\Data and \bin\CoreData are definitely populated with lots of stuff.  I didn't check whether _everything_ is in there but lots of stuff is being copied.

I tried building everything "in source" in that \Build directory you have in the source tree.  It didn't fix anything, the menu screen looks the same.

ResourcePrefixPaths handling was recently changed in Urho3D.  Now it takes a semicolon ; separated list of multiple search paths.  I wonder if something is going wrong with that.  Earlier I was having a problem finding resources.  I traced it into \Urho3D\Source\Urho3D\Engine\Engine.cpp and was setting breakpoints there to see what was going on.  However, things look fine in that section now.  Don't think that's it.

Hmm your Readme.md says to look at http://urho3d.wikia.com/wiki/Creating_a_new_Urho3D_Project for how to build.  So that's where you got this Build/bin idea from.  I wonder if those docs are basically wrong now.  If they aren't, I'll try to convince the devs to make them wrong, because in-source builds are bad CMake style.  :-)

I will try building against straight Urho3D 1.5 to see if that makes any difference.

**Comment by damu** [comment]
> Hmm your Readme.md says to look at http://urho3d.wikia.com/wiki/Creating_a_new_Urho3D_Project for how to build. So that's where you got this Build/bin idea from. I wonder if those docs are basically wrong now. 

I wrote that page ;-) It's not yet updated to Urho 1.5 and should be incorrect by now. I just managed today to build Urho 1.5, Urho's CMake scripts are acting weird on my machine and I had to use a more manual CMake configuration.

Building inside or outside shouldn't make a difference.
I just made a new build directory outside ("S:\dev\Urho-Sample-Platformer_Build" with "S:\dev\Urho-Sample-Platformer" being the source) and redid CMake and rebuild USP. It copied all files properly and USP is working properly. Can you try to copy the files from bin/Data manually?

**Comment by bvanevery** [comment]
I see that you got rid of \Build\bin in favor of \bin.

Building against Urho3D-1.5 makes no difference.  Nor does manually copying the \Data and \CoreData from the source tree to the \bin in the build directory tree.  I think this proves that copying is not the problem.

**Comment by bvanevery** [comment]
Do you have a bunch of environment variables pertaining to Urho3D?  I don't.  I wonder if an environment difference could be changing the behavior of finding resources.  Like, are you finding Urho3D resources rather than USP resources?

**Comment by bvanevery** [comment]
Did a little debug tracing.  In the following code:

```
void gs_main_menu::HandlePlayPressed(Urho3D::StringHash eventType,Urho3D::VariantMap& eventData)
{
    Text* t=(Text*)lv_levels->GetSelectedItem();
    if(!t)
        return;

    globals::instance()->game_states[0].reset(new gs_playing(("maps/"+t->GetVar("filename").GetString()+".xml").CString()));
}
```

when Play is pressed, t is always 0 and HandlePlayPressed simply returns.  So the mystery would be why no text is put into t.

This line in gs_main_menu.cpp

```
        fs.ScanDir(result,"Data/maps/","*",SCAN_FILES,true);
```

returns a result with a Size() of 0.  So, none of the logic following it is performed.

**Comment by damu** [comment]
I already thought that the list isn't there because the files aren't there. Copying them into "Data/maps" (seen from the execution dir) should help. Does it also not work if you start the program directly (not from the IDE) when there is a ./Data/maps/ with the map files? Maybe Visual Studio has a weird execution dir and the files are therefore not found.
The only environment variable I have is Urho3D_Home and that doesn't help finding the map files as they are not in Urho but in USP.

**Comment by bvanevery** [comment]
Deep in the bowels of Urho3D's FileSystem.cpp in the function ScanDirInternal is this line:

```
    HANDLE handle = FindFirstFileW(WString(path + "*").CString(), &info);
```

which constructs a string "Data/maps/*", runs a Windows function FindFirstFileW, and returns an invalid HANDLE.  As there's no global path here, I assume this function works with a working directory that is set somewhere else.  Somehow, that working directory is wrong.

Using File Explorer outside of VS2015 and simply clicking on Urho_Sample_Platformer_d.exe does bring improvement.  The background is still black, but now there are 3 menu entries inside the big rectangle.  level_1 level_2 level_3.  The background of the rectangle they reside in, is black.  The mouse will move the selection arrow at the left to point to whichever level I want.  Leaving it on level_1, I press Play.  I get a black screen with text at the top that is ticking off a FPS counter and some other data.  The music also changes to "drums".  If I press ESC I get a menu.  I select Quit and leave the game.

So, something somewhere is feeding the wrong paths, for more things than the menus.

I notice you copy the cache into a static global.  What if it isn't thread safe?

I've traced a lot of resource path finding stuff that seems to be working just fine.  It is difficult to trace all of it though.  The many layers of functions make it hard to see what's going on.

**Comment by damu** [comment]
Ah some progress.
I just found out that Urho prints every resource it can't find in the Urho3D.log like:

> [Sun Nov 29 17:38:15 2015] ERROR: Could not find resource Materials/flag_pole.xml
> [Sun Nov 29 17:38:15 2015] ERROR: Could not find resource Materials/flag_cloth.xml
> [Sun Nov 29 17:38:15 2015] ERROR: Could not find resource Materials/Particle.xml

Can you check if there are such errors? There should be none. Try with directly starting the program, as it seems to at least find the three maps then.
Also you can try to change the working directory in visual studio to the directory of the .exe:
http://codeyarns.com/2013/12/30/how-to-change-working-directory-in-visual-studio/
There is some way to make a visual studio .user file via CMake with a changed working directory, we could try to do that if changing the working directory works.

**Comment by bvanevery** [comment]
The log is revealing!
[Urho3D.log.txt](https://github.com/gawag/Urho-Sample-Platformer/files/46736/Urho3D.log.txt)
You have GLSL shaders for your levels and not HLSL shaders.
I compiled my Urho3D for DX11.  Your CMake builds against it without checking whether OpenGL is actually available.
Now the question becomes, whose error is this?  Is there a known mechanism that's supposed to be checked, or is this in developer limbo?  And I think something should be filed upstream to make this predicament easier for people to resolve.
I will build an OpenGL version and see if it solves the problems.

**Comment by damu** [comment]
> You have GLSL shaders for your levels and not HLSL shaders.

Yes! Were you using DirectX? That's currently not supported. ;-) Didn't think of that.
I'm using OpenGL to be more platform independent.
My custom shaders are currently only GLSL. It may be not that difficult to port them to HLSL. Maybe just copying and renaming them and seeing if functions have other names. There may be converter tools for GLSL<->HLSL
That AutoExposure shader should work though, it's shipped with Urho. Also I don't know what those "Failed to create input layout" errors mean.

I'm currently setting up Urho and USP in a Windows 10 virtual machine to see if my CMake errors are due to my main Windows 7 system being old and weird. Maybe I'll also setup DirectX.

**Comment by bvanevery** [comment]
Ok building against OpenGL version of Urho3D, now I've got a nicely animated background.  But within VS2015 the rectangle for the menu is still blank and Play still does nothing.

When I run USP from its build \bin directory at a command prompt, outside of VS2015, everything works.  It's slow as a dog, 1.5 FPS on this cheesy laptop, but it does work.

So, building against OpenGL solves a problem, but not the problem.  At least it provides a clue, that however the background scene stuff is loaded, that's what actually works.

When VS2015 is used, the log shows up as C:\Users\BVANEVRY\devel\build\Urho-Sample-Platformer-gl\Urho3D.log.  Note that this is not the \bin directory.  So maybe you are right, that the VS2015 working directory needs to be set by CMake somehow.  I see no resource load failures in the log file.  
[Urho3D.log.txt](https://github.com/gawag/Urho-Sample-Platformer/files/46796/Urho3D.log.txt)

**Comment by damu** [comment]
> It's slow as a dog, 1.5 FPS on this cheesy laptop, but it does work.

Okay... Is that only in the level or also in the main menu? The terrain shader are quite heavy. Though even with my old graphics card (GTX 660, quite outdated now) it was quite fluid. The third map should be less heavy. There should be some kind of options to toggle to less-heavy-materials. Doesn't need to be a full settings menu, could just be a checkbox in the main menu.

There seems to be some way to make a Visual Studio specific file and do some CMake magic to get another working directory into Visual Studio, but I don't really understand the stuff I found and also don't have Visual Studio right now.
I just pushed a (dirty) fix that may work.

Still working on my Urho build with DirectX in my Virtual Machine. Found out that it's 3D capabilities are rather weird, but should be good enough for build testing. The Urho samples don't work (just black), one (other) game mostly worked and one other game crashed.

**Comment by bvanevery** [comment]
Comedies with OpenGL on old laptops get even better.  I've got one that doesn't even offer OpenGL 2.0.  That's actually a Windows 10 problem, as Intel didn't bother to update its OpenGL capabilities for this 2008 era business class laptop.  It may have worked for Windows 7 just fine.  It's worth nothing, however, that there was a period where OpenGL Intel drivers for Windows were extreme crap.  Small wonder they weren't willing to move that code forwards to Windows 10.  Anyways I'm looking into how USP can fail more gracefully when the available OpenGL sucks, as I think it'll happen as people take advantage of free Windows 10 updates.  I've found the place where the log error is generated, in Urho3D\Source\Urho3D\Graphics\OpenGL\OGLGraphics.cpp.  

```
            URHO3D_LOGERROR("OpenGL 2.0 is required");
```

However the function it occurs in, returns void.  I don't think there's a runtime mechanism to know that this has failed.

**Comment by bvanevery** [comment]
Ok, your hack of switching to \bin unconditionally before doing anything else, does make the VS2015 working directory problem go away.  I doubt that's a good idea long term though as it'll probably have unintended consequences.  I'll file an issue about figuring out what's going on with CMake and VS2015 so it's not forgotten.

Incidentally, a venerable NVIDIA GeForce 8600M GT achieves a massive 4.5 FPS.  3x improvement over the business class AMD integrated laptop!

**Comment by damu** [comment]
> Ok, your hack of switching to \bin unconditionally before doing anything else, does make the VS2015 working directory problem go away. I doubt that's a good idea long term though as it'll probably have unintended consequences.

As long as there is no bin/ folder inside the bin/ folder there should be no problem, still hacky though. 

I just looked up your card and compared that to my old one ;-) http://www.videocardbenchmark.net/compare.php?cmp[]=1275&cmp[]=2152
4119 points vs 178 points, that's a big difference. My current GTX 770 has 6146 points and USP really feels ~50% faster, FPS still drop when I spawn multiple torches (via L) but it holds a bit more as before. Those points seem to be quite accurate. #18
