### ISSUE TITLE
Add support for DirectX

### ISSUE THREAD

**Issue by bvanevery** [gawag/Urho-Sample-Platformer#15]
USP only has GLSL shaders, so an Urho3D built with OpenGL is required.  Urho3D doesn't currently export any way to know that's true, so a mismatched build will blithely go along and produce an .exe that runs but does almost nothing.  Documenting the need for OpenGL in Readme.md would be a helpful stopgap until a detection mechanism becomes available in Urho3D proper.  https://github.com/urho3d/Urho3D/issues/1066 has been submitted in the hope of a simple mechanism like URHO3D_OPENGL defined in a .h file, but that of course isn't available in the Urho3D 1.5 release.

**Comment by damu** [comment]
Managed to build Urho and USP with DirectX9 on WIndows 10.
I'm now trying to convert the GLSL shader to HLSL. Seems more complicated as just some simple renaming.

**Comment by bvanevery** [comment]
Hm, well, good luck!  I'm still a shader noob.  Have the 3d graphics background but it was from a pre-shader era.  Maybe this article can help you with GLSL --> HLSL.
https://technet.microsoft.com/en-us/subscriptions/dn166865.aspx
As for mechanical approaches, I found a few HLSL --> GLSL converters but not the other way around.
Some things maybe could do GLSL --> HLSL, but I found 1 article by a guy saying he was aware of no such beast.  So I was a bit leery of trying to chase through a pile of tools and command line options to determine it firsthand.  Seemed more productive to just learn more about GLSL first.

**Comment by damu** [comment]
HLSL done. Works great in DirectX9. HLSL is not that different from GLSL. I used the LitSolid.hlsl as a new base for the HLSL shader.
DirectX 11 is creating a lot of errors, the Urho samples are also not working with DirectX 11. Could be an issue of my VM.
I'm currently trying to update all the materials and shader stuff with the files from Urho 1.5. DirectX 11 seems to be broken with them too, DirectX9 and OpenGL are not yet tested, I'm on it.

**Comment by damu** [comment]
Data files updated. DirectX 9 and OpenGL are both working.
Updating the files seems to not have changed anything.

**Comment by damu** [comment]
Had the idea that DirectX 11 may just be broken inside my virtual machine and rebuild and retested USP outside. It runs there, but displays several errors and has big graphical glitches.

```
[Sun Dec 06 05:22:02 2015] ERROR: Failed to create input layout for shader Shadow(), missing element mask 8
[Sun Dec 06 05:22:02 2015] ERROR: Failed to create input layout for shader Shadow(SKINNED), missing element mask 8
[Sun Dec 06 05:22:03 2015] ERROR: Failed to create input layout for shader level_1_terrain(DIRLIGHT PERPIXEL SHADOW VERTEXCOLOR), missing element mask 8
```

**Comment by bvanevery** [comment]
I can build and run DX11 just fine on my laptop, good job on that!  However the ground doesn't exist.  The sky is fine, and so is the main character.  Menu screen is fine too.  Log shows exactly the same 3 failures as you listed above.

**Comment by damu** [comment]
I can see the ground but the colors are totally weird and it's flickering. Sometimes it's just black or white and sometimes like it should be but without lighting. Level 3 (the asteroid field) looks mostly normal most of the time. There are stripes on the asteroids and sometimes they also have this black or white only, but less weird as in level 1 or 2.
The Urho samples work fine though.

**Comment by bvanevery** [comment]
I don't know much of anything about shaders or HLSL.  But the 3 log errors are coming from Urho3D\Source\Urho3D\Graphics\Direct3D11\D3D11VertexDeclaration.cpp in the VertexDeclaration constructor:

```
    ID3D11InputLayout* d3dInputLayout = 0;
    const PODVector<unsigned char>& byteCode = vertexShader->GetByteCode();

    graphics->GetImpl()->GetDevice()->CreateInputLayout(&elementDescs[0], (UINT)elementDescs.Size(), &byteCode[0],
        byteCode.Size(), &d3dInputLayout);
    if (d3dInputLayout)
        inputLayout_ = d3dInputLayout;
    else
        URHO3D_LOGERRORF("Failed to create input layout for shader %s, missing element mask %d",
            vertexShader->GetFullName().CString(), vertexShader->GetElementMask() & ~vbElementMask);
}
```

An "element mask" is declared in D3D11ShaderVariation.h

```
    /// Vertex element mask for vertex shaders. Zero for pixel shaders.
    unsigned elementMask_;
```

Also in D3D11VertexBuffer.h

```
    /// Vertex element bitmask.
    unsigned elementMask_;
```

CreateInputLayout is a DX11 function.  Need to figure out what it wants, but I'm bored for now.

**Comment by bvanevery** [comment]
I tried the most recent Urho3D in GitHub, hoping errors would magically go away.  There are many instances of a new error now:

```
[Thu Dec 10 03:13:10 2015] ERROR: Failed to create read-only depth-stencil view for texture
```

This comes from D3D11Texture2D.cpp

```
        // Create also a read-only version of the view for simultaneous depth testing and sampling in shader
        depthStencilViewDesc.Flags = D3D11_DSV_READ_ONLY_DEPTH;
        graphics_->GetImpl()->GetDevice()->CreateDepthStencilView((ID3D11Resource*)object_, &depthStencilViewDesc,
            (ID3D11DepthStencilView**)&renderSurface_->readOnlyView_);

        if (!renderSurface_->readOnlyView_)
        {
            URHO3D_LOGERROR("Failed to create read-only depth-stencil view for texture");
            return false;
        }
```

Also only 1 instance of the previous kind of error, with a bit different wording:

```
[Thu Dec 10 03:13:42 2015] ERROR: Failed to create input layout for shader level_1_terrain(DIRLIGHT PERPIXEL VERTEXCOLOR), missing element mask 8
```

**Comment by bvanevery** [comment]
Pulling Urho3D today, the textures have now started working.  The .log file is much shorter and there are no errors.  I think the problem must have been on the Urho3D side, and something has changed to fix it.

**Comment by damu** [comment]
It works in newest Urho from GitHub?? Dang... I hope they make an update to the latest stable. Don't want to be working on an (possible unstable) Urho from Git again.
That would also explain why I didn't get it to work and couldn't find anything that looked wrong in my shaders or other material stuff. Weird though that the Urho samples worked.

**Comment by bvanevery** [comment]
They didn't say anything, but I think my request for a HRESULT logging mechanism + quoting the bit of code where I was finding all the read-only stencil errors, may have jogged their memory about something.  Thus it is probably good to file issues in their tracker.  At least as long as you can get it to the point of being sure "it's not you".  I couldn't tell whether it was your code or their code, but filing an issue may have triggered a fix.  They seem to fix things pretty fast when they know something is wrong.

Or it may have been coincidence, I don't know.  What I do know, is that Linux and I think OSX get continuous automated testing, but Windows does not, owing to the free service they're using.

**Comment by bvanevery** [comment]
Must have been coincidence.  With the latest pull of Urho3D, USP is completely junked.  Log has 3 of this kind of error again:

```
[Mon Dec 14 14:20:25 2015] ERROR: Failed to create input layout for shader Shadow(), missing element mask 8
[Mon Dec 14 14:20:25 2015] ERROR: Failed to create input layout for shader Shadow(SKINNED), missing element mask 8
[Mon Dec 14 14:20:26 2015] ERROR: Failed to create input layout for shader level_1_terrain(DIRLIGHT PERPIXEL SHADOW VERTEXCOLOR), missing element mask 8
```

It is right to keep this issue closed though.  DirectX support was added.  Something is happening on Urho3D's end.  It keeps changing every time I pull.  Should file an upstream bug with Urho3D, just can't quite figure out what to say.  Same 3 failures when built against Urho3D 1.5.

**Comment by damu** [comment]
I'm also currently trying to activate C++11 in this simpler Sample Project for the wiki. Activating C++11 seems to somehow deactivate DirectX 11 and it tries to build for DirectX 9. DirectX 11 seems to be really broken ATM.
http://urho3d.prophpbb.com/post9587.html

**Comment by bvanevery** [comment]
I'll follow up on this in the forum.  Having general conversation about different issues in the issue tracker is really confusing.

**Comment by damu** [comment]
Yeah I already looked if there is a message personal system on Github, doesn't seem like it. Though that issue was about C++11 and not about DirectX 11.
