### ISSUE TITLE
always select URHO3D_OPENGL in CMake

### ISSUE THREAD

**Issue by bvanevery** [gawag/Urho-Sample-Platformer#19]
There's currently no reason to give the user a choice about using OpenGL, D3D9, or D3D11 in the CMake build.  Might as well have it always choose OpenGL.  If the user selects something else, could provide a warning message like "hey dude, it ain't gonna work.  And I hope you built your Urho3D with OpenGL while you were at it."

**Comment by damu** [comment]
DirectX 9 is now supported.

**Comment by bvanevery** [comment]
Well since you decided to jump right into DirectX stuff, this issue is obsolete.
