### ISSUE TITLE
gettimeofday() missing in Windows

### ISSUE THREAD

**Issue by 1vanK** [gawag/Urho-Sample-Platformer#8]
and project dont' compile. I used http://stackoverflow.com/questions/10905892/equivalent-of-gettimeday-for-windows for it

**Comment by damu** [comment]
I'm developing on Windows and it works perfectly. Are you using VisualStudio? Which version? I'm using MinGW. Getting a relative precise time in a platform independent way is super difficult in C++. I know that C++11 has got some time function, I'll try to switch to those in the next days.

**Comment by damu** [comment]
Just commited an update version of the timer class that uses the C++11 std::chrono. Should be more portable now. Does that also work for your setup?

**Comment by 1vanK** [comment]
Visual Studio 2013. The new version successfully compiles and runs.

**Comment by damu** [comment]
Ah that's good. Heard that Visual Studio 2013 is the first version that is supposed to support most of C++11. Former versions like 2012 are not and this may not work with <2013.
